### PR TITLE
sync with CTDS

### PR DESCRIPTION
**Pull request by grugna**

### CODE REVIEW

**Comment by grugna** [comment]
@paulmurdoch19 in reviewing this PR beside resolving the conflicts and testing it to make sure nothing else broke you should also make a separate but  related PR to update our services (amanuensis, pcdcanalysistool ...) similarly to what they changes are for fence and sheepdog respectively.

**Review by paulmurdoch19 — APPROVED** [review]

**Comment by grugna** [comment]
@paulmurdoch19 could you resolve the conflicts, test it and merge it please.

**Comment by paulmurdoch19** [comment]
Sorry, I was trying to merge it into another branch to bring it down to test I thought it would let me use the web editor if I approved it but I think it’s to complicated and I will have to use the cli

**Comment by grugna** [comment]
no need to apologize, thank you

**Pull request merged**
